name: note_defn
description: Dart library for Note Class definitions
version: 0.0.1
# author: Jaime Loeuf <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

# dev_dependencies:
#   pedantic: ^1.0.0
#   test: ^1.0.0
